require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6.3
  Exclude:
    - config/environments/*
    - config/initializers/*
    - db/schema.rb
    - db/seeds.rb
    - bin/*
    - spec/services/org_service_update/cascade_spec.rb
    - lib/tasks/db.rake

  DisplayCopNames: true
  DisplayStyleGuide: true


Rails:
  Enabled: true

Rails/DynamicFindBy:
  Enabled: false

Rails/TimeZone:
  Enabled: false

Rails/EnumUniqueness:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

AsciiComments:
  Enabled: false

ClassLength:
  Enabled: false

MethodLength:
  Enabled: false

Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/PredicateName:
  NameWhitelist:
    - is_a?

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Layout/AlignParameters:
  Enabled: false

LineLength:
  Max: 120

Lint/UnifiedInteger:
  Description: 'Use Integer instead of Fixnum or Bignum'
  Enabled: false

Metrics/BlockLength:
  Description: 'Avoid long blocks with many lines.'
  Exclude:
    - "spec/**/*.rb"
    - "**/*.rake"
    - "db/migrate/*.rb"

Rails/HttpPositionalArguments:
  Exclude:
    - spec/acceptance/**/*_spec.rb
